server:
    port: 8083
spring:
    application:
        name: sbo-service  
    cloud:
        consul:
            enabled: true
            host: localhost
            port: 8500
            config:
                enabled: true
    jpa:
        generate-ddl: true
        show-sql: true
        hibernate:
            ddl-auto: update
        properties:
            javax:
                persistence:
                    schema-generation:
                        create-source: metadata
            hibernate: 
                hbm2ddl:
                    auto: update
                dialect: org.hibernate.dialect.PostgreSQLDialect
                jdbc: 
                    lob:
                        non_contextual_creation: true
    datasource:
        url: jdbc:postgresql://localhost:5432/postgres
        username: postgres
        password: 1234
        continue-on-error: false
    flyway: 
        locations: classpath:db/migration
        url: jdbc:postgresql://localhost:5432/postgres
        schemas: postgres
        user: postgres
        password: 1234
    mvc:
        throw-exception-if-no-handler-found: true
    resources:
        add-mappings: false